sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libboost-test-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - ./autogen.sh

script:
  - ./configure && make && make check

after_failure:
  - if [ -f tests/tests.log ]; then cat tests/tests.log; fi
  - if [ -f tests/stdtests.log ]; then cat tests/stdtests.log; fi
