sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libboost-test-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

# Install Boost 1.60 on OSX, using a custom GCC-compiled bottle if need be
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CXX" == "clang++" ]]; then brew install boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CXX" == "g++" ]]; then wget 'https://github.com/Malvineous/travis-homebrew-bottle/releases/download/boost1.60-gcc/boost-1.60.0_2.mavericks.bottle.tar.gz' && brew install *.bottle.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - ./autogen.sh

script:
  - ./configure && make && make check

after_failure:
  - if [ -f tests/tests.log ]; then cat tests/tests.log; fi
  - if [ -f tests/stdtests.log ]; then cat tests/stdtests.log; fi
