version: 2.0.0-beta{build}

# Build on each push, not on each tag creation.  This stops a double build
# when deployment creates a new tag.
skip_tags: true

install:
- ps: >-
    # Download nuget.exe >= 3.4.4 as earlier versions produce corrupted native .nupkg files

    $nugetPath = "$($env:USERPROFILE)\nuget.exe"

    (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', $nugetPath)


    # Make the nuget.exe folder come first in the path, so it gets picked up before anything else

    $env:Path = $env:USERPROFILE + ";" + $env:Path


    # Download the CoApp tools.

    $msiPath = "$($env:USERPROFILE)\CoApp.Tools.Powershell.msi"

    (New-Object Net.WebClient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', $msiPath)


    # Install the CoApp tools from the downloaded .msi.

    Start-Process -FilePath msiexec -ArgumentList /i, $msiPath, /quiet -Wait


    # Make the tools available for later PS scripts to use.

    $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'

    Import-Module CoApp

nuget:
  disable_publish_on_pr: true

build_script:
- cmd: >-
    "%VS140COMNTOOLS%\VsMSBuildCmd.bat"

    appveyor-retry nuget restore win32\libgamecommon.sln

    appveyor-retry nuget update win32\libgamecommon.sln

    FOR %%T IN (v140,v140_xp) DO ( FOR %%P IN (x86,x64) DO ( FOR %%C IN (Debug,Release) DO ( FOR %%F IN (libgamecommon,libgamecommon-tests) DO ( echo *** Building %%F as %%T/%%P/%%C *** && msbuild win32\%%F\%%F.vcxproj /p:Configuration=%%C /p:Platform=%%P /p:PlatformToolset=%%T /p:SolutionDir=..\ /v:minimal /nologo || EXIT 1 ) ) ) )

before_deploy:
- ps: >-
    # This is the CoApp .autopkg file to create.

    $autopkgFile = "win32\libgamecommon\libgamecommon.autopkg"


    # Get the ".autopkg.template" file, replace "@version" with the Appveyor version number, then save to the ".autopkg" file.

    cat ($autopkgFile + ".template") | % { $_ -replace "@version", $env:appveyor_build_version } > $autopkgFile


    # Use the CoApp tools to create NuGet native packages from the .autopkg.

    Write-NuGetPackage $autopkgFile


    # Push all newly created .nupkg files as Appveyor artifacts for later deployment.

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
- provider: NuGet
  api_key:
    secure: 9Rk3FyZ1qSjw0eyhiyhsfyOpir/jfoV6t1IkPA4L3VA/fLPMpmNdjOxDaniqoDxL
  artifact: /.*\.nupkg/
  on:
    branch: master
